# Generated by Django 4.2.3 on 2024-08-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilo', '0004_alter_workout_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
