# Generated by Django 2.0.5 on 2018-05-30 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0003_auto_20180529_0004'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songtag',
            unique_together={('song', 'tag')},
        ),
    ]
