# Generated by Django 2.0.5 on 2018-05-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0005_auto_20180530_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_acquired',
            field=models.DateTimeField(null=True),
        ),
    ]
