# Generated by Django 2.0.5 on 2018-06-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0006_auto_20180530_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
