# Generated by Django 2.0.5 on 2019-12-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0008_auto_20180603_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='export_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='last_export',
            field=models.DateTimeField(null=True),
        ),
    ]
