# Generated by Django 2.0.5 on 2019-12-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0009_add_export_columns_to_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hex_code', models.CharField(default='ffffff', max_length=8)),
                ('white_text', models.BooleanField(default=False)),
            ],
        ),
    ]
