# Generated by Django 2.0.5 on 2019-12-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0010_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
