# Generated by Django 2.0.5 on 2019-12-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0011_tag_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_mix',
            field=models.BooleanField(default=False),
        ),
    ]
