# Generated by Django 2.0.5 on 2019-12-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0012_album_is_mix'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
