# Generated by Django 2.0.5 on 2020-02-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0015_song_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
