# Generated by Django 2.0.5 on 2020-02-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0016_song_year'),
        ('rhyme', '0015_multidisc_support'),
    ]

    operations = [
    ]
