# Generated by Django 2.0.5 on 2020-02-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0017_merge_20200215_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='export_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='last_export',
            field=models.DateTimeField(null=True),
        ),
    ]
