# Generated by Django 2.0.5 on 2020-07-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0019_add_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='plex_filename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
