# Generated by Django 2.0.5 on 2020-07-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0020_song_plex_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='plex_guid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='plex_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
