# Generated by Django 2.0.12 on 2020-07-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0021_auto_20200704_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, null=True)),
                ('plex_guid', models.CharField(max_length=255, null=True)),
                ('plex_key', models.CharField(max_length=255, null=True)),
                ('song_filters', models.TextField(null=True)),
                ('album_filters', models.TextField(null=True)),
                ('omni_filter', models.TextField(null=True)),
            ],
        ),
    ]
