# Generated by Django 2.0.12 on 2020-07-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0023_playlist_plex_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='last_play',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='plex_key',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
