# Generated by Django 3.1.4 on 2022-01-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0024_add_play_columns_to_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-date_acquired']},
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(db_index=True, max_length=127),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('disc', 'ordinal', 'album')},
        ),
    ]
