# Generated by Django 4.2.3 on 2023-08-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0026_remove_song_plex_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion', models.BooleanField(default=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhyme.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhyme.song')),
            ],
            options={
                'unique_together': {('playlist', 'song')},
            },
        ),
    ]
