# Generated by Django 4.2.3 on 2026-09-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0030_rename_last_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(null=True),
        ),
    ]
