# Generated by Django 3.1.7 on 2023-03-08 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('F', 'Follower'), ('L', 'Leader')], max_length=2)),
                ('division', models.CharField(choices=[('0', 'Newcomer'), ('N', 'Novice'), ('I', 'Intermediate'), ('A', 'Advanced'), ('AS', 'All Star'), ('C', 'Champion')], max_length=2)),
                ('_round', models.CharField(choices=[('P', 'Prelims'), ('Q', 'Quarters'), ('S', 'Semis'), ('F', 'Finals')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RowScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orange.competition')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orange.person')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orange.event'),
        ),
        migrations.CreateModel(
            name='ColumnScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=3)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orange.person')),
                ('row_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orange.rowscore')),
            ],
        ),
    ]
