# Generated by Django 3.1.7 on 2023-03-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowscore',
            name='promote',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='_round',
            field=models.CharField(choices=[('P', 'Prelim'), ('Q', 'Quarter'), ('S', 'Semi'), ('F', 'Final')], max_length=2),
        ),
    ]
