# Generated by Django 3.1.7 on 2023-03-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orange', '0002_auto_20230311_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnscore',
            name='judge',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='competition',
            name='event',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='rowscore',
            name='competitor',
            field=models.CharField(max_length=63),
        ),
    ]
