# Generated by Django 3.1.7 on 2023-03-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orange', '0003_auto_20230311_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='role',
            field=models.CharField(choices=[('F', 'Follower'), ('L', 'Leader')], max_length=2, null=True),
        ),
    ]
