# Generated by Django 2.0.5 on 2018-05-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='energy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='mood',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
