# Generated by Django 2.0.5 on 2018-05-30 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastes', '0004_auto_20180530_0058'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('song', 'album')},
        ),
    ]
