# Generated by Django 2.0.5 on 2018-06-03 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastes', '0007_auto_20180602_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-id']},
        ),
    ]
