from django.urls import path

from rhyme.views import (
    albums,
    album_list,
    album_export,
    artist_choices,
    csv_songs,
    csv_tags,
    index,
    json_albums,
    json_artists,
    json_colors,
    json_discs,
    json_songs,
    json_tags,
    json_tracks,
    matrix,
    matrix_json,
    network,
    network_json,
    playlist_choices,
    plex_in,
    song_list,
    song_update,
    song_export,
    tag_choices,
)

urlpatterns = [
    path('', index, name='index'),
    path('albums/', albums, name='albums'),
    path('albums/list/', album_list, name='album_list'),
    path('albums/export/', album_export, name='album_export'),
    path('artists/choices/', artist_choices, name='artist_choices'),
    path('csv/song', csv_songs, name='csv_songs'),
    path('csv/tag', csv_tags, name='csv_tags'),
    path('json/albums', json_albums, name='json_albums'),
    path('json/artists', json_artists, name='json_artists'),
    path('json/colors', json_colors, name='json_colors'),
    path('json/discs', json_discs, name='json_discs'),
    path('json/songs', json_songs, name='json_songs'),
    path('json/tags', json_tags, name='json_tags'),
    path('json/tracks', json_tracks, name='json_tracks'),
    path('playlist/choices/', playlist_choices, name='playlist_choices'),
    path('plex/in/<slug:api_key>/', plex_in, name='plex_in'),
    path('songs/list/', song_list, name='song_list'),
    path('songs/update/', song_update, name='song_update'),
    path('songs/export/', song_export, name='song_export'),
    path('stats/matrix/', matrix, name='matrix'),
    path('stats/matrix/json/', matrix_json, name='matrix_json'),
    path('stats/network/', network, name='network'),
    path('stats/network/json/', network_json, name='network_json'),
    path('tags/choices/', tag_choices, name='tag_choices'),
]
