# Generated by Django 2.0.12 on 2020-12-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['-day']},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='workout',
            name='ordering',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateField(unique_for_date=True),
        ),
    ]
