# Generated by Django 2.0.12 on 2020-12-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miles', '0002_add_orderings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='time',
            new_name='seconds',
        ),
    ]
